/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controler.AeroportController;
import Controler.VolController;
import Model.VolModel;
import java.util.ArrayList;
import View.Vol;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hanine
 */
public class Home_All_Vol extends javax.swing.JFrame {

            ArrayList<VolModel> alu = new ArrayList<VolModel>();
            VolController uc = new VolController();
    /**
     * Creates new form Home_All_Vol
     */
    public Home_All_Vol() {
        initComponents();
        alu = (ArrayList<VolModel>) uc.getAll();
        DefaultTableModel model = new DefaultTableModel();
        tableVol.setModel(model);

        model.addColumn("AeroportDepart");
        model.addColumn("AeroportArrive");
        model.addColumn("dateDepart");
        model.addColumn("dateArrive");
        model.addColumn("heureDepart");
        model.addColumn("heureArrive");
        model.addColumn("reservable");

        System.out.println("Size of alu: " + alu.size());
        AeroportController aeroportController = new AeroportController();
        for (VolModel u : alu) {
           System.out.println("Adding row: " + u.getAeroportDepart().getIdAeroport() + ", " + u.getAeroportArrive().getIdAeroport() + ", " + u.getDateDepart() + ", " + u.getDateArrive() + ", " + u.getHeureDepart() + ", " + u.getHeureArrive() + ", " + u.isReservable());
            String aeroportDepartName = aeroportController.getAeroportNameById(u.getAeroportDepart().getIdAeroport());
            String aeroportArriveName = aeroportController.getAeroportNameById(u.getAeroportArrive().getIdAeroport());
            model.addRow(new Object[]{
                aeroportDepartName,
                aeroportArriveName,
                u.getDateDepart(),
                u.getDateArrive(),
                u.getHeureDepart(),
                u.getHeureArrive(),
                u.isReservable()
            });
        }

        System.out.println("Number of columns: " + model.getColumnCount());
        System.out.println("Number of rows: " + model.getRowCount());

        // Refresh the table to reflect changes
        model.fireTableDataChanged();
    
        tableVol.setModel(model);
    }
    
    private VolModel getSelectedVolModel() {
    int selectedRow = tableVol.getSelectedRow();
    if (selectedRow != -1) {
        return alu.get(selectedRow);
    }
    return null;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVol = new javax.swing.JTable();
        AddVol = new javax.swing.JButton();
        UpdVol = new javax.swing.JButton();
        DelVol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        tableVol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVol.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableVol.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableVol);

        AddVol.setBackground(new java.awt.Color(153, 153, 255));
        AddVol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddVol.setForeground(new java.awt.Color(255, 255, 255));
        AddVol.setText("Ajouter Vol");
        AddVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVolActionPerformed(evt);
            }
        });

        UpdVol.setBackground(new java.awt.Color(153, 153, 255));
        UpdVol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UpdVol.setForeground(new java.awt.Color(255, 255, 255));
        UpdVol.setText("Modifier Vol");
        UpdVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdVolActionPerformed(evt);
            }
        });

        DelVol.setBackground(new java.awt.Color(153, 153, 255));
        DelVol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DelVol.setForeground(new java.awt.Color(255, 255, 255));
        DelVol.setText("Supprimer Vol");
        DelVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelVolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddVol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdVol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DelVol, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddVol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdVol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DelVol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVolActionPerformed
         new Vol().setVisible(true);
    }//GEN-LAST:event_AddVolActionPerformed

    private void UpdVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdVolActionPerformed
        VolModel selectedVol = getSelectedVolModel();
        if (selectedVol != null) {
       
        VolUpdate volForm = new VolUpdate(selectedVol);
        volForm.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne");
    }
    }//GEN-LAST:event_UpdVolActionPerformed

    private void DelVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelVolActionPerformed
         VolController uc = new VolController();
        int selectedRow=tableVol.getSelectedRow();
        if(selectedRow!=-1){
            DefaultTableModel tableModel=(DefaultTableModel)tableVol.getModel();
            tableModel.removeRow(selectedRow);
           VolModel selectedVol = alu.get(selectedRow);
           System.out.println(selectedVol.getIdVol());
            uc.delete(selectedVol);

            System.out.println(selectedRow);
             JOptionPane.showMessageDialog(this, "Vol supprimé avec succès", "Succès", JOptionPane.INFORMATION_MESSAGE);
             
            
        }else{
            JOptionPane.showMessageDialog(this, "Veuillez selectionner une ligne");
        }
    }//GEN-LAST:event_DelVolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_All_Vol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_All_Vol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_All_Vol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_All_Vol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_All_Vol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVol;
    private javax.swing.JButton DelVol;
    private javax.swing.JButton UpdVol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVol;
    // End of variables declaration//GEN-END:variables
}
