/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controler.AeroportController;
import javax.swing.JOptionPane;
import Controler.VolController;
import Model.AeroportModel;
import Model.VolModel;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Hanine
 */
public class VolUpdate extends javax.swing.JFrame {

    /**
     * Creates new form Vol
     */
  
    private VolModel selectedVol;
    
    VolUpdate(VolModel selectedVol) {
    this.selectedVol = selectedVol;
    initComponents();
       
   // Create an instance of AeroportController
    AeroportController aeroportController = new AeroportController();

    // Obtenez les noms des aéroports en utilisant les IDs stockés dans VolModel
    int idAeroportDepart = selectedVol.getAeroportDepart().getIdAeroport();
    int idAeroportArrive = selectedVol.getAeroportArrive().getIdAeroport();

    System.out.println("ID Aeroport Depart: " + idAeroportDepart);
    System.out.println("ID Aeroport Arrive: " + idAeroportArrive);

    String nomAeroportDepart = aeroportController.getAeroportNameById(idAeroportDepart);
    String nomAeroportArrive = aeroportController.getAeroportNameById(idAeroportArrive);

    System.out.println("Nom Aeroport Depart: " + nomAeroportDepart);
    System.out.println("Nom Aeroport Arrive: " + nomAeroportArrive);

    // Créez des instances AeroportModel en utilisant les noms
    AeroportModel aeroportDepartModel = new AeroportModel();
    aeroportDepartModel.setNomAeroport(nomAeroportDepart);

    AeroportModel aeroportArriveModel = new AeroportModel();
    aeroportArriveModel.setNomAeroport(nomAeroportArrive);
    // Obtenez les modèles actuels des JComboBox
    DefaultComboBoxModel<String> modelDep = (DefaultComboBoxModel<String>) selectArpDep.getModel();
    DefaultComboBoxModel<String> modelArr = (DefaultComboBoxModel<String>) selectArpArr.getModel();
    //remplir formulaire
    // Ajoutez les noms des aéroports aux modèles
    modelDep.addElement(nomAeroportDepart);
    modelArr.addElement(nomAeroportArrive);
    inpDateArr.setText(selectedVol.getDateArrive());
    inpDateDep.setText(selectedVol.getDateDepart());
    inpHeureDep.setText(selectedVol.getHeureDepart());
    inpHeureArr.setText(selectedVol.getHeureArrive());
    cdVol.setText(selectedVol.getCodeVol());
    if (selectedVol.getReservable()==1) {
        rdoOui.setSelected(true);
    } else {
        rdoNon.setSelected(true);
    }
     AeroportController ac = new AeroportController();
         
        ArrayList<AeroportModel> listeAeroports = new ArrayList<>();
        listeAeroports = (ArrayList<AeroportModel>) ac.getAll();

        // Ajouter les aéroports au JComboBox
        for (AeroportModel aeroport : listeAeroports) {
            selectArpDep.addItem(aeroport.getNomAeroport()); 
            selectArpArr.addItem(aeroport.getNomAeroport()); 
        }
}

    private VolUpdate() {
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addVol = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inpDateArr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inpHeureArr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inpDateDep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inpHeureDep = new javax.swing.JTextField();
        rdoOui = new javax.swing.JRadioButton();
        rdoNon = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnModifier = new javax.swing.JButton();
        selectArpArr = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        selectArpDep = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cdVol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        addVol.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        addVol.setForeground(new java.awt.Color(153, 153, 255));
        addVol.setText("Modifer Vol");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Aeroport Arrivé");

        inpDateArr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpDateArrActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Date Arrivée");

        inpHeureArr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpHeureArrActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Heure Départ");

        inpDateDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpDateDepActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Réservable");

        inpHeureDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpHeureDepActionPerformed(evt);
            }
        });

        rdoOui.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rdoOui.setForeground(new java.awt.Color(153, 153, 255));
        rdoOui.setText("Oui");
        rdoOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoOuiActionPerformed(evt);
            }
        });

        rdoNon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rdoNon.setForeground(new java.awt.Color(153, 153, 255));
        rdoNon.setText("Non");
        rdoNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("Heure Arrivée");

        btnModifier.setBackground(new java.awt.Color(153, 153, 255));
        btnModifier.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnModifier.setForeground(new java.awt.Color(255, 255, 255));
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Date Départ");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 255));
        jLabel9.setText("Aeroport Départ");

        selectArpDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectArpDepActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 255));
        jLabel11.setText("Code Vol");

        cdVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdVolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addVol)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(58, 58, 58)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(58, 58, 58)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectArpDep, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectArpArr, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdoOui)
                                .addGap(33, 33, 33)
                                .addComponent(rdoNon))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnModifier)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inpHeureArr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                                    .addComponent(inpHeureDep, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inpDateDep, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inpDateArr, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cdVol, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addVol)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectArpDep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectArpArr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpDateArr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpDateDep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpHeureDep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpHeureArr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cdVol))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoOui)
                    .addComponent(rdoNon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpDateArrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpDateArrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpDateArrActionPerformed

    private void inpHeureArrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpHeureArrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpHeureArrActionPerformed

    private void inpDateDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpDateDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpDateDepActionPerformed

    private void inpHeureDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpHeureDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpHeureDepActionPerformed

    private void rdoOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoOuiActionPerformed
       rdoOui.setSelected(true);
    }//GEN-LAST:event_rdoOuiActionPerformed

    private void rdoNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNonActionPerformed
        rdoNon.setSelected(true);
    }//GEN-LAST:event_rdoNonActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
            String aeroportDepart = selectArpDep.getSelectedItem().toString();
            String aeroportArrive = selectArpArr.getSelectedItem().toString();

            // Create an instance of AeroportController
            AeroportController aeroportController = new AeroportController();

            int idAeroportDepart = aeroportController.getAeroportIdByName(aeroportDepart);
            int idAeroportArrive = aeroportController.getAeroportIdByName(aeroportArrive);
            
            System.out.println("TEST "+idAeroportDepart);

            // Create AeroportModel instances using the IDs
            AeroportModel aeroportDepartModel = new AeroportModel();
            aeroportDepartModel.setIdAeroport(idAeroportDepart);

            AeroportModel aeroportArriveModel = new AeroportModel();
            aeroportArriveModel.setIdAeroport(idAeroportArrive);
            
            
            String dateDepart = inpDateArr.getText();
            String dateArrive = inpDateDep.getText();
            String heureDepart = inpHeureDep.getText();
            String heureArrive = inpHeureArr.getText();
            String codeVol = cdVol.getText();
            boolean reservable = rdoOui.isSelected();
            int reservableInt = rdoOui.isSelected() ? 1 : 0;
            System.out.println("Aeroport Depart: " + aeroportDepart);
            System.out.println("Aeroport Arrive: " + aeroportArrive);
            System.out.println("Date Depart: " + dateDepart);
            System.out.println("Date Arrive: " + dateArrive);
            System.out.println("heure Depart: " + heureDepart);
            System.out.println("heure Arrive: " + heureArrive);
            System.out.println("reservable: " + reservable);
            // Get the ID of the selected vol
            int selectedVolId = selectedVol.getIdVol();

            // Create a VolModel object with the updated information
            VolModel updatedVol = new VolModel(aeroportDepartModel, aeroportArriveModel, dateDepart, dateArrive, heureDepart, heureArrive,codeVol, reservableInt);
        
            updatedVol.setIdVol(selectedVolId); // Set the ID of the selected vol
           
                System.out.println("selectedVolId"+updatedVol);
            // Call the update method
            VolController volController = new VolController();
            boolean success = volController.update(updatedVol, selectedVolId);
      
            // to Check if the update was successful
            if (success) {
                JOptionPane.showMessageDialog(this, "Flight updated successfully");
            this.setVisible(false);
            Home_All_Vol homeAllVolFrame = new Home_All_Vol();
            homeAllVolFrame.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Error updating flight");
            }

           
    }//GEN-LAST:event_btnModifierActionPerformed

    private void selectArpDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectArpDepActionPerformed
        
 
    }//GEN-LAST:event_selectArpDepActionPerformed

    private void cdVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdVolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdVolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addVol;
    private javax.swing.JButton btnModifier;
    private javax.swing.JTextField cdVol;
    private javax.swing.JTextField inpDateArr;
    private javax.swing.JTextField inpDateDep;
    private javax.swing.JTextField inpHeureArr;
    private javax.swing.JTextField inpHeureDep;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdoNon;
    private javax.swing.JRadioButton rdoOui;
    private javax.swing.JComboBox<String> selectArpArr;
    private javax.swing.JComboBox<String> selectArpDep;
    // End of variables declaration//GEN-END:variables

    
}
